  <header>
        <a href="{{ site.github.url }}"> <h1>{{ site.title | default: site.github.repository_name }}</h1> </a>

	{% if site.logo %}
	  <img src="{{site.logo}}" alt="Logo"></img>
    {% endif %}

	<p>{{ site.description | default: site.github.project_tagline }}</p>
